export const getProjectsPageRoute = () => '/'
export const getProfilePageRoute = () => '/profile'
export const getNotificationsPageRoute = () => '/notifications'
export const getChatsPageRoute = () => '/messages'
export const getResourcesPageRoute = () => '/resources'
export const getSpecialistsPageRoute = () => '/resources/specialists'
export const getInvestorsPageRoute = () => '/resources/investors'
export const getEquipmentPageRoute = () => '/resources/equipment'
export const getRoomsPageRoute = () => '/resources/rooms'
export const getSettingsPageRoute = () => '/settings'

export const getSignInRoute = () => '/sign-in'
export const getSignUpRoute = () => '/sign-up'
export const getSignOutRoute = () => '/sign-out'
